#! /bin/bash

echo
echo
echo "______________S T A R T   J O B_____________________"
echo
echo ' PL/1  ----->  Asswmbler    c o m p i l i n g'
echo "continue?(y/n)"
read OTV
if [ "$OTV" = "y" ]
then
  echo
  ../build/komppl.exe ex11.pli
else
  echo
  exit
fi

echo
echo
echo ' Assembler  ----->  Object image   c o m p i l i n g'
echo "continue?(y/n)"
read OTV
if [ "$OTV" = "y" ]
then
  echo
  ../build/kompassr.exe ex11.ass
else
  echo
  exit
fi

echo
echo
echo ' Load, run and debug Object image  '
echo "continue?(y/n)"
read OTV
if [ "$OTV" = "y" ]
then
  echo
  ../build/absloadm.exe spis.mod
else
  echo
  exit
fi

echo
echo
echo "______________F I N I S H     J O B__________________"
